export const navigation = [
  // { text: 'Home', href: '/' },
  { text: 'Bins', href: '/bins' },
  { text: 'Contact', href: '/contact' },
  { text: 'Dishwasher', href: '/dishwasher' },
  { text: 'Heating', href: '/heating' },
  { text: 'Internet', href: '/internet' },
  { text: 'Doors', href: '/doors' },
  { text: 'Lawn', href: '/lawn' },
  { text: 'Oven', href: '/oven' },
  { text: 'Security', href: '/security' },
  { text: 'TV', href: '/tv' },
  { text: 'Washing Machine', href: '/washing-machine' },
  { text: 'Furniture', href: '/furniture' },
  { text: 'Appliances', href: '/appliances' },
]
