import { HouseItem } from '@/lib/types'

export const applianceItems: HouseItem[] = [
  {
    label: 'Ovens',
    imageSources: ['oven1'],
    brand: 'Electrolux',
    model: 'EOF6H46X2',
    href: 'https://www.electrolux.co.uk/kitchen/cooking/ovens/oven/eof6h46x2/',
  },
  {
    label: 'Dishwasher',
    brand: 'Electrolux',
    model: 'KEAF7200L',
    imageSources: ['dishwasher1', 'dishwasher2', 'dishwasher3'],
    href: 'https://www.electrolux.co.uk/kitchen/dishwashing/dishwashers/built-in-dishwasher/keaf7200l/',
  },
  {
    label: 'Fridge',
    imageSources: ['fridge1'],
    brand: 'Electrolux',
    model: 'LXB3AF82R',
    href: 'https://www.electrolux.co.uk/kitchen/cooling/refrigerators/small-refrigerator/',
  },
  {
    label: 'Freezer',
    imageSources: ['freezer1', 'freezer2'],
    brand: 'Electrolux',
    model: 'LYB3NE82R',
    href: 'https://www.electrolux.co.uk/kitchen/cooling/freezers/built-in-freezer/lyb3ne82r/',
  },
  {
    label: 'Kitchen Hot Water',
    imageSources: ['kitchen-hws1', 'kitchen-hws2'],
    brand: 'Baxi',
    model: 'Baxi Assure System',
  },
  {
    label: 'Car Charger',
    imageSources: ['car-charger1', 'car-charger12'],
    brand: 'Zaptec',
    model: 'Zaptec Go',
    href: 'https://www.zaptec.com/en-uk/charging-solutions/zaptec-go',
  },
  {
    label: 'TV',
    imageSources: ['tv1'],
    brand: 'LG',
    model: '49UJ634V',
    href: 'https://www.lg.com/uk/tvs-soundbars/smart-tvs/49uj634v/',
  },
  {
    label: 'Range Hood',
    imageSources: ['range2', 'range1'],
    brand: 'Elica',
    model: 'Elite 14 (60)',
    href: 'https://www.elica.com/GB-en/hoods/integrated/elite-14',
  },
  {
    label: 'Washing Machine',
    imageSources: ['washing-machine1'],
    brand: 'Zanussi',
    model: 'ZWD86SB4PW',
    href: 'https://www.zanussi.co.uk/laundry/laundry/washer-dryers/free-standing-washer-dryer/zwd86sb4pw2/',
  },
  {
    label: 'Upstairs Hot Water',
    imageSources: [
      'upstairs-hws1',
      'upstairs-hws2',
      'upstairs-hws3',
      'upstairs-hws4',
    ],
    brand: 'Albion Ultrasteel',
    model: 'AUI210ERP',
    href: 'https://www.kingspan.com/gb/en/products/hot-water-cylinders/stainless-unvented-cylinders/ultrasteel-indirect/?v=210',
  },
  {
    label: 'Hob',
    imageSources: ['hob1'],
    brand: 'Electrolux',
    model: 'LIT604',
    href: 'https://www.electrolux.co.uk/kitchen/cooking/hobs/induction-hob/lit6042/',
  },
]
